"""column type changed to clicktype

Revision ID: 026e2ade134a
Revises: d418db84b74f
Create Date: 2018-09-19 22:00:14.573313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026e2ade134a'
down_revision = 'd418db84b74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_logs', sa.Column('clicktype', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_behavior_logs_clicktype'), 'behavior_logs', ['clicktype'], unique=False)
    op.drop_index('ix_behavior_logs_type', table_name='behavior_logs')
    op.drop_column('behavior_logs', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_logs', sa.Column('type', sa.INTEGER(), nullable=True))
    op.create_index('ix_behavior_logs_type', 'behavior_logs', ['type'], unique=False)
    op.drop_index(op.f('ix_behavior_logs_clicktype'), table_name='behavior_logs')
    op.drop_column('behavior_logs', 'clicktype')
    # ### end Alembic commands ###
