"""BehaviorLogs table added

Revision ID: d73f4484c441
Revises: 8222fe91dc14
Create Date: 2018-09-19 21:04:33.194631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73f4484c441'
down_revision = '8222fe91dc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_logs_timestamp'), 'behavior_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_behavior_logs_type'), 'behavior_logs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_logs_type'), table_name='behavior_logs')
    op.drop_index(op.f('ix_behavior_logs_timestamp'), table_name='behavior_logs')
    op.drop_table('behavior_logs')
    # ### end Alembic commands ###
