"""files table

Revision ID: fdc4f505a0ee
Revises: 0ecce2f51101
Create Date: 2018-10-24 17:36:20.672854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc4f505a0ee'
down_revision = '0ecce2f51101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexed_file')
    # ### end Alembic commands ###
